name: HoneyServer
main: Honey\Main
version: 1.1.0
api:
  - 3.0.0
  - 3.0.0-ALPHA11
load: STARTUP
author: towa0131
authors: [towa0131]
description: HoneyServer System Plugin
website: https://honey-mc.net
commands:
 stats:
  description: "ユーザーのステータスを確認します"
  usage: "/stats <name>"
 report:
  description: "違反ユーザーを報告します"
  usage: "/report"
  aliases: [rp]
 guild:
  description: "ギルド関係のコマンドです"
  usage: "/guild [join|quit|create|invite|deny|destroy]"
  aliases: [g]
permissions:
 admin.command:
  default: op