---
#はにー鯖設定ファイル
#trueで有効になります
#falseで無効になります

#DBの設定
DB:
 address: 127.0.0.1
 user: root
 password: password
 database: mysql
 timeout: 10

#サーバーの設定
Server:
 #サーバー名のカスタム
 motd: §6{servername} §5[§a{nowplayers}§5/§a{maxplayers}§5]
 #デバッグモードの有効化
 debug: false
 #圧縮レベルの設定
 compression-level: 7
 #一時インベントリデータの保存方法
 #db = データベース
 #file = ファイル
 #cache = キャッシュ変数
 tempinventory-savetype: file
 #一時インベントリデータの保存先(保存方法でfileを選んだときのみ有効)
 tempinventory-filepath: /plugins/HoneyServer/
 #自動再起動の有効化
 auto-restart: false
 #サーバー再起動時の自動参加の有効化
 auto-join: true

# ユーザー設定
User:
 #デフォルトの言語
 default-lang: jpn
 #初期はにい
 default-honey: 0

#ワールドの設定
Level:
 #デフォルトワールド名
 default-world: world
 #待機ワールド
 wait-world: waitlobby

#パスワード管理設定
Password:
 #ハッシュの種類の設定
 hash-type: md5
 #ハッシュ回数
 hash-count: 1000

...